### PR TITLE
API compatibility tests. Cross compile to 2.13. Fix some API mismatch…

### PR DESCRIPTION
**Pull request by mikla**
- API compatibility tests. 
- Cross compile to 2.13. #40 
- Fix some API mismatch behaviour. 
- Create moment instant by specifying parameters in an object. #35 
- Fix getters for Duration.

### CODE REVIEW

**Review by vpavkin — APPROVED** [review]
awesome! LGTM. 
Any plans for CI build?

**Comment by mikla** [comment]
@vpavkin yup-yup, will handle it ;)

**Comment by mikla** [comment]
I guess I don't have enough permissions to add Travis CI to this repo...

**Comment by aappddeevv** [comment]
Is this getting a version bump or will it be the same version as now?

**Comment by vpavkin** [comment]
@aappddeevv It technically can't be the same since it's already published. After it's merged I'll release a new version

**Comment by aappddeevv** [comment]
Thanks!

**Comment by aappddeevv** [comment]
Did this get pushed out to repos?

**Comment by vpavkin** [comment]
@aappddeevv yep, just published as 0.10.0, should be in maven central soon

**Pull request merged**
