### PR TITLE
Added a few missing methods like toDate() and add()/subtract()

### PR DESCRIPTION
**Pull request by dainkaplan**

### CODE REVIEW

**Comment by dainkaplan** [comment]
Not sure if this is actually where you want these methods, but this did the job for me!

**Comment by tindzk** [comment]
Looks great. Perhaps you could also merge all constants with `Unit`?

**Comment by dainkaplan** [comment]
Oh. It looks like the existing `Unit` is the same as my `Units` object. So I can probably just delete mine? Since Scala has a built in `Unit` type, I think it might be best to avoid the naming conflict though, and rename it to "Units".

**Comment by tindzk** [comment]
Although I haven't encountered any conflicts, this may be a good idea indeed.

**Pull request merged**
