### PR TITLE
Add missing mappings: Moment.weekdaysShort, Date.isSame, Getters.date

### PR DESCRIPTION
**Pull request by nremond**

### CODE REVIEW

**Comment by tindzk** [comment]
Great, thanks!

**Comment by nremond** [comment]
May I also ask you this question: I don't get it why most methods in `Getters.scala` are returning Double?

For instance: `def year(): Double = js.native` should actually be `def year(): Int = js.native`. 

`Int` type is well supported in Scala.js it seems from here: http://www.scala-js.org/doc/interoperability/types.html

Am I missing something ?

**Comment by tindzk** [comment]
Good point. It should be safe to change those getters to return `Int` instead.

**Comment by nremond** [comment]
Opened a PR for that.

**Pull request merged**
