### PR TITLE
added diff

### PR DESCRIPTION
**Pull request by gilcu2**
Added diff between Date function

### CODE REVIEW

**Comment by tindzk** [comment]
Thanks! Could you also overload `diff()` with a `unit` parameter?

**Comment by gilcu2** [comment]
Done

**Comment by tindzk** [comment]
I believe that you have to overload it manually, because default parameters are not supported by Scala.js façades.

**Comment by gilcu2** [comment]
Like that it is supported [?]

import org.widok.moment._
var last=Moment()
target.onmousedown =
  (e: dom.MouseEvent) => {
    val actual=Moment()
    val dife=actual.diff(last)
    val difeSec=actual.diff(last,"s")
    println("Last click was: "+dife+" sec: "+difeSec)
  }

Last click was: 1602 sec: 1
Last click was: 5427 sec: 5

**Comment by tindzk** [comment]
Ok, I must have been wrong then. Thanks!

**Pull request merged**
